fn main() -> Result<(), Box<dyn std::error::Error>> {
    act_bridge_gen::build_shim(&act_bridge_gen::PluginConfig {
        assembly_name: "ActBridgeExample.ACT".into(),
        native_dll_name: "ffxiv_plugin.dll".into(),
        metadata: act_bridge_gen::PluginMetadata {
            file_description: "Example Rust plugin for Advanced Combat Tracker".into(),
            product_name: "act-bridge-gen example".into(),
            company_name: "act-bridge-gen contributors".into(),
            legal_copyright: "Licensed under GPL-3.0-or-later".into(),
            comments: "Generated by act-bridge-gen".into(),
            ..Default::default()
        },
    })
}
